/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/player.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useEnvironment } from "@react-three/drei"

export function Model(props) {
  const { nodes, materials } = useGLTF('/player.glb')
  const env = useEnvironment({ preset: "city" })
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Cone004_1.geometry} material={materials['Material.001']}  material-envMap={env} />
        <mesh geometry={nodes.Cone004_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/player.glb')
