/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/punisher.glb -o src/gltfjsx/punisher.jsx 
*/
import * as THREE from 'three'

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/punisher.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={new THREE.EdgesGeometry(nodes.Cube.geometry, 30)}>
        <lineBasicMaterial color="black" />
      </lineSegments>
      <lineSegments geometry={new THREE.EdgesGeometry(nodes.Selection001.geometry, 30)} position={[0, 0.01, 0]}>
        <lineBasicMaterial color="black" />
      </lineSegments>
    </group>
  )
}

useGLTF.preload('/punisher.glb')
