/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/punisher.glb -o src/gltfjsx/punisher.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/punisher.glb')
  return (
    <group layers={[1]} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Selection001.geometry} material={materials['Material.001']} position={[0, 0.01, 0]} />
    </group>
  )
}

useGLTF.preload('/punisher.glb')
