/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/untitled.glb -o src/gltfjsx/untitled.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.001']} scale={0.426} />
    </group>
  )
}

useGLTF.preload('/untitled.glb')
