/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/untitled.glb -o src/gltfjsx/untitled.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import CustomLine from '../components/CustomLine'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <CustomLine geometry={nodes.Icosphere.geometry} />
      <CustomLine geometry={nodes.Icosphere002.geometry} scale={0.426} />
      {/* <lineSegments geometry={new THREE.EdgesGeometry(nodes.Icosphere002.geometry, 30)} scale={0.426}>
        <lineBasicMaterial color="black" />
      </lineSegments>  */}
    </group>
  )
}

useGLTF.preload('/untitled.glb')
